name: Batch Register (10 runs)

on:
  workflow_dispatch:
    inputs:
      count:
        description: '执行次数'
        required: false
        default: '10'
        type: string
      interval:
        description: '间隔秒数'
        required: false
        default: '2'
        type: string

jobs:
  register:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2小时超时
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager faker pyyaml requests
          pip install undetected-chromedriver || echo "undetected-chromedriver 安装失败"

      - name: Configure for headless
        run: |
          # 修改配置为无头模式 + Chrome
          sed -i 's/headless: false/headless: true/' config/config.yaml
          sed -i 's/type: "edge"/type: "chrome"/' config/config.yaml
          cat config/config.yaml | grep -E "headless|type"

      - name: Run batch registration
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          cd src/runners
          # 使用 echo 模拟交互输入: 次数 + 间隔
          echo -e "${{ inputs.count }}\n${{ inputs.interval }}" | python main.py

      - name: Upload accounts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accounts
          path: accounts.json
          if-no-files-found: ignore

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            *.png
            src/runners/*.png
          if-no-files-found: ignore
